"use client";

import Image from "next/image";
import Link from "next/link";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import { robotoSlab, serif } from "@/lib/fonts";
import Footer from "@/components/Footer";
import Nav from "@/components/Nav";
import SoftBackground from "@/components/SoftBackground";

const markdownComponents = {
  h2: ({ node, ...props }) => (
    <h2
      className="text-lg md:text-xl font-bold text-black mt-8 mb-3 first:mt-0 tracking-tight"
      style={serif}
      {...props}
    />
  ),
  p: ({ node, ...props }) => <p className="text-[1.05rem] text-gray-700 leading-relaxed mb-4 last:mb-0" {...props} />,
  strong: ({ node, ...props }) => <strong className="font-semibold text-black" {...props} />,
  ol: ({ node, ...props }) => <ol className="list-decimal pl-5 space-y-2 my-4" {...props} />,
  ul: ({ node, ...props }) => <ul className="list-disc pl-5 space-y-2 my-4" {...props} />,
  li: ({ node, ...props }) => <li className="text-[1.05rem] text-gray-700 leading-relaxed" {...props} />,
};

export default function BriefView({ content, formattedDate }) {
  return (
    <main className="relative flex flex-col w-full min-h-screen overflow-x-clip">
      <span className={robotoSlab.className} hidden aria-hidden />

      <div className="fixed inset-0 z-0 pointer-events-none gradient-background">
        <SoftBackground />
      </div>

      <Nav />

      <section className="relative z-10 flex-1 w-full px-4 py-14 md:py-20 pt-24 md:pt-28 pb-12 md:pb-16">
        <div className="max-w-[680px] mx-auto">
          <div className="rounded-2xl border border-[#e8e4dc]/90 bg-white p-6 md:p-10 shadow-[0_2px_12px_rgba(0,0,0,0.04)]">
            <div className="flex justify-center mb-8">
              <Image
                src="/logos/RT-Logo-New.svg"
                alt="Radical Thinking"
                width={56}
                height={56}
                priority
              />
            </div>

            <p className="text-xs font-semibold tracking-[0.22em] uppercase text-[#8a8780] text-center mb-2">
              A conversation with RT-BOT
            </p>
            <p className="text-sm text-gray-500 text-center mb-8">{formattedDate}</p>

            <div className="rt-divider mb-8" />

            <div className="brief-body">
              <ReactMarkdown remarkPlugins={[remarkGfm]} components={markdownComponents}>
                {content}
              </ReactMarkdown>
            </div>

            <div className="rt-divider my-8" />

            <div className="text-center">
              <p className="text-sm text-gray-600 leading-relaxed mb-4">
                This brief was generated by RT-BOT, the AI agent for Radical Thinking.
              </p>
              <Link
                href="/chat"
                className="inline-flex items-center text-sm font-semibold text-black hover:opacity-70 transition-opacity"
              >
                Start your own conversation →
              </Link>
            </div>
          </div>
        </div>
      </section>

      <Footer />
    </main>
  );
}
