export const portfolio = [
    {
        title: "FluffyFriends",
        category: "AI Product Engineering",
        description: "Autonomous AI pet portrait studio that generates 8K personalised artwork in under 5 minutes using n8n and Google Gemini.",
        link: "/work/fluffyfriends",
        slug: "fluffyfriends",
        tags: ["AI", "Automation"],
        image: "/Images/Portfolio/fluffyfriends.webp",
        live: "https://fluffyfriends.online",
        overview: "FluffyFriends is an AI-powered pet portrait platform built by Radical Thinking. It generates personalised, high-resolution artwork from a customer photo using a fully automated workflow built on n8n and Google Gemini. No human intervention required.",
        challenge: "The market is flooded with competitors generating generic, costumed pet portraits. AI image generation is inherently unpredictable. Delivering a substandard image destroys brand trust and generates immediate refund requests. The system needed to personalise artwork and guarantee output quality without human oversight.",
        solution: "FluffyFriends runs entirely on a self-hosted n8n infrastructure. Every stage of the customer lifecycle is handled by interconnected AI agents communicating via authenticated webhooks. From smart photo validation using Gemini Flash to multi-image prompting and automated quality scoring, the system ensures only high-quality outputs reach the customer.",
        outcome: "A fully autonomous digital product that scales without adding headcount. Name-personalisation baked into the image commands a premium over generic competitors. Single-portrait entry points are engineered to convert into bundle packages via Stripe session management.",
        facts: [
            { label: "Technology", value: "Next.js, Supabase, n8n, Google Gemini, Stripe, Cloudinary" },
            { label: "Delivered", value: "Web platform, automated AI workflow, payment integration" },
            { label: "Status", value: "Live" },
            { label: "URL", value: "fluffyfriends.online" },
        ],
    },
    {
        title: "Kahulife",
        category: "Next-Generation Pet Management Platform",
        description: "A comprehensive digital ecosystem and AI companion for dedicated pet guardians.",
        link: "/work/kahulife",
        slug: "kahulife",
        tags: ["AI", "Digital Platforms"],
        image: "/Images/Portfolio/kahulife.webp",
        live: "",
        overview: "Kahulife is an upcoming, highly advanced pet management platform designed for pet owners who view their animals as integral members of the family unit. Radical Thinking designed and built the complete MVP architecture.",
        challenge: "Pet data is fundamentally fragmented across physical vaccine cards, disparate vet clinics, and generic tracking apps. Pet parents lack a singular, centralized intelligent ecosystem capable of tracking health metrics, managing medical reminders, and giving accurate, breed-specific medical guidance without scrolling through unreliable search engines.",
        solution: "Radical Thinking engineered a centralized digital ecosystem centered around an automated Digital Pet Passport. The platform safely stores entire historical vaccination records and medication schedules, tracks behavioral moods, and schedules automated veterinary appointments. Crucially, we integrated a custom, breed-intelligent AI chatbot trained to provide hyper-specific advice tailored to the pet's age, weight, and genetic history.",
        outcome: "A highly sophisticated digital pet care infrastructure currently scaling through its active beta phase. The foundational platform is engineered to seamlessly integrate with broader commercial pet services, providing a hyper-stable, high-value utility framework positioned for a massive upcoming commercial launch.",
        facts: [
            { label: "Status", value: "Active beta" },
            { label: "Focus", value: "Pet health, AI companion, digital passport" },
        ],
    },
    {
        title: "Tommy & Ellie",
        category: "Generative AI Art Concept Studio",
        description: "An early-stage exploratory e-commerce venture validating automated print-on-demand generative art workflows.",
        link: "/work/tommy-ellie",
        slug: "tommy-ellie",
        tags: ["AI", "E-Commerce"],
        image: "/Images/Portfolio/Tommy-Ellie.webp",
        live: "",
        overview: "The Tommy & Ellie Shop was built as a cutting-edge exploratory sandbox by Radical Thinking during the early, foundational wave of generative image model technology.",
        challenge: "Early generative AI art was widely misunderstood and largely unmonetized. The challenge was to explore the end-to-end capabilities of early image models, understand how to convert prompt engineering into highly realistic, museum-quality art, and test consumer appetite for AI-generated pet products across global marketplaces like Etsy and Redbubble.",
        solution: "Radical Thinking built an interactive storytelling concept studio. We engineered highly complex prompt sequences to generate stylized, ultra-realistic dog portraits styled as legendary Samurais and vibrant Bollywood characters. These assets were automatically mapped onto physical merchandise and listed across global print-on-demand platforms.",
        outcome: "The project served as an invaluable research and development milestone, generating consistent direct-to-consumer sales while proving the operational viability of generative storytelling. The deep insights gained from this workflow laid the explicit technical foundation for Radical Thinking's future high-scale automation products.",
        facts: [],
    },
    {
        title: "Animal Intelligence",
        category: "Data-Driven Animal Welfare Platform",
        description: "An advanced conceptual framework leveraging AI data analytics to optimize animal shelter management and regional adoption workflows.",
        link: "/work/animal-intelligence",
        slug: "animal-intelligence",
        tags: ["AI", "Data"],
        image: "/Images/Portfolio/animal-intelligence.webp",
        live: "",
        overview: "Animal Intelligence is a visionary, forward-thinking initiative conceptualized by Radical Thinking to harness artificial intelligence in empowering government bodies, veterinary clinics, and rescue shelters.",
        challenge: "Animal welfare and shelter management in the Middle East faces significant logistical and educational hurdles. Regional shelters and government bodies lack centralized, intelligent data systems to effectively track stray animal populations, manage complex trap-neuter-return (TNR) colonies, or optimize the regional pet adoption lifecycle.",
        solution: "Radical Thinking architected a comprehensive digital platform powered by advanced AI data engines. Designed to process massive regional datasets, the platform provides predictive insights into adoption patterns, tracks colony health trends, and optimizes resource distribution for shelters. The foundational brand footprint and AI-driven conceptual frameworks were fully developed internally by Radical Thinking.",
        outcome: "An incredibly precise, high-utility platform architecture currently positioned in its pre-launch beta phase. The baseline branding, core data models, and strategic government-alignment parameters are fully secured, establishing a ready-to-scale framework poised to revolutionize regional animal welfare logistics upon official launch.",
        facts: [
            { label: "Status", value: "Pre-launch beta" },
        ],
    },
    {
        title: "Microsoft AI",
        category: "Conversational Registration Engine",
        description: "An early-stage, native AI chatbot designed as the automated registration gateway for Microsoft's premiere technical workshops.",
        link: "/work/microsoft-ai",
        slug: "microsoft-ai",
        tags: ["AI", "Interactive"],
        image: "/Images/Portfolio/microsoft-ai.webp",
        live: "",
        overview: "In an elite joint venture alongside AI Networks, Radical Thinking was tapped by Microsoft to develop the user acquisition gateway for their inaugural Chatbot in a Day technical developer workshops.",
        challenge: "Microsoft was introducing its foundational, early-stage conversational AI models to the global developer community. To showcase the true power of the technology, the event registration process couldn't rely on a generic static web form; it needed to be a living, breathing proof-of-concept that demonstrated the product's value instantly.",
        solution: "Radical Thinking engineered a native conversational AI chatbot that lived directly on the workshop landing page. Instead of filling out inputs, developers registered for the event by simply holding a natural, real-time text conversation with the AI, which intelligently captured, validated, and processed their registration data in the background.",
        outcome: "This project stood as one of the earliest public-facing examples of conversational utility, deployed at the very dawn of native enterprise AI infrastructure. The chatbot successfully handled high-volume developer sign-ups, providing a powerful, self-demonstrating marketing experience that perfectly set the stage for Microsoft's workshop.",
        facts: [],
    },
    {
        title: "WebinarLife",
        category: "End-to-End Enterprise Event Infrastructure",
        description: "A fully managed, white-glove virtual event platform built to bypass traditional corporate procurement friction.",
        link: "/work/webinarlife",
        slug: "webinarlife",
        tags: ["Digital Platforms"],
        image: "/Images/Portfolio/Webinarlife.webp",
        live: "",
        overview: "Launched during global lockdown periods, WebinarLife was engineered by Radical Thinking as a premium, fully managed virtual event infrastructure tailored for corporations and high-level government entities.",
        challenge: "During the height of remote-work mandates, organizations desperately needed to communicate securely with audiences, but were severely bottlenecked by rigid corporate procurement cycles. Larger companies and government bodies could not quickly buy expensive, long-term software subscriptions or manage complex digital event production internally.",
        solution: "Radical Thinking built a full-service, pay-per-event utility model. Leveraging enterprise-grade webinar engines, we handled the entire lifecycle from A to Z. Our team managed custom brand design, promotional artwork creation, digital invitation sequences, live technical event production, real-time poll management, automated follow-ups, and post-event analytics.",
        outcome: "The service achieved tremendous success by allowing enterprise procurement departments to completely outsource event overhead without getting locked into software licenses. Every event was fully tailored to the client's corporate styling guidelines, maintaining flawless operational delivery until physical events safely resumed.",
        facts: [],
    },
    {
        title: "Simon Snelder",
        category: "Bespoke Financial Personal Brand Ecosystem",
        description: "A premium, multi-channel personal brand architecture enabling an elite financial advisor to scale independently.",
        link: "/work/simon-snelder",
        slug: "simon-snelder",
        tags: ["Branding"],
        image: "/Images/Portfolio/Simonsnelder.webp",
        live: "",
        overview: "Simon Snelder is an elite financial advisor who retained Radical Thinking to orchestrate his transition from corporate placement to a fully independent, elite solo advisory practice.",
        challenge: "Moving away from an established corporate umbrella requires immediate, undeniable personal brand authority. The challenge was to build a solo identity from absolute scratch that projected institutional-grade security and financial intellect, while maintaining a deeply warm, trustworthy, and accessible personal touch.",
        solution: "Radical Thinking built a cohesive, multi-touchpoint brand universe. We developed a sophisticated, warm corporate logo and identity guidelines, which were then systematically rolled out across an integrated digital ecosystem. This included a premium advisory website, custom podcast production templates, webinar visual systems, social media assets, and high-end print prospectus layouts.",
        outcome: "The launch established Simon Snelder as an elite, authoritative independent voice in the financial space. The comprehensive marketing collateral and professional digital presence drove immediate market differentiation, generating a significant influx of high-net-worth client acquisitions immediately following release.",
        facts: [],
    },
    {
        title: "Austability Web",
        category: "Enterprise Digital Infrastructure",
        description: "An enterprise-grade corporate web platform built on Umbraco CMS, optimized for secure institutional B2B lead generation.",
        link: "/work/austability-web",
        slug: "austability-web",
        tags: ["Strategy", "Digital Platforms"],
        image: "/Images/Portfolio/Austability.webp",
        live: "",
        overview: "Austability is a highly sophisticated, multi-faceted industrial organization. Radical Thinking executed a comprehensive digital transformation, revamping their core web infrastructure to match the scale and security demands of an institutional audience.",
        challenge: "Operating within a deeply technical, high-stakes sector, Austability's existing web presence failed to accurately present their full service capabilities securely to an institutional audience. The project demanded absolute clarity out of intricate processes and a platform built for enterprise-grade trust.",
        solution: "Radical Thinking designed and deployed a beautiful, enterprise-grade corporate website built on the highly secure Umbraco CMS framework, specifically optimized for secure institutional B2B lead generation. The architecture was engineered to present complex service capabilities with clarity while meeting strict security and scalability requirements.",
        outcome: "The new, ultra-secure Umbraco web platform successfully modernized Austability's digital footprint, driving an immediate uptick in high-value corporate inquiries. Paired with a complementary corporate video asset, the brand achieved a cohesive, institutional-grade market presence.",
        facts: [
            { label: "Technology", value: "Umbraco CMS" },
            { label: "Delivered", value: "Enterprise corporate website" },
        ],
    },
    {
        title: "Austability Branding",
        category: "Strategic Brand Identity",
        description: "A comprehensive corporate brand overhaul for a multi-faceted industrial organisation.",
        link: "/work/austability-branding",
        slug: "austability-branding",
        tags: ["Branding", "Strategy"],
        image: "/Images/Portfolio/Austability-logo.webp",
        live: "",
        overview: "Austability is a highly sophisticated, multi-faceted industrial organisation. Radical Thinking led a comprehensive brand overhaul to bring clarity, institutional authority, and visual cohesion to their market presence.",
        challenge: "Operating within a deeply technical, high-stakes sector, Austability's customer-facing messaging was overly complex. Their visual identity failed to communicate their full service capabilities with the clarity and trust that institutional audiences expect.",
        solution: "Radical Thinking developed a refined corporate brand system and visual identity built for B2B credibility. Logo treatment, messaging hierarchy, and marketing collateral were aligned so external communications matched the precision of the organisation's technical capabilities.",
        outcome: "The refreshed brand identity gave Austability a cohesive, institutional-grade market presence. Paired with a corporate video and enterprise web platform, the full transformation shortened the sales cycle and drove an uptick in high-value corporate inquiries.",
        facts: [
            { label: "Delivered", value: "Corporate brand identity and visual system" },
        ],
    },
    {
        title: "Austability Video",
        category: "Enterprise Video Production",
        description: "High-end cinematic storytelling translating complex industrial capabilities into immediate conceptual clarity.",
        link: "/work/austability-video",
        slug: "austability-video",
        tags: ["Video"],
        image: "/Images/Portfolio/austability-video.webp",
        youtubeId: "IRZKSagPaQ4",
        videoCtaLabel: "Watch on YouTube",
        live: "",
        overview: "As part of a broader brand transformation for Austability, Radical Thinking produced a high-fidelity corporate video engineered to translate what the organization stands for in a matter of minutes.",
        challenge: "Operating within a deeply technical, high-stakes sector, Austability's customer-facing messaging was overly complex. Prospects needed immediate conceptual clarity before engaging with sales, without wading through dense technical documentation.",
        solution: "Working with a pre-existing voiceover and script, Radical Thinking engineered a seamless blend of custom 2D/3D animation, high-end stock sequences, and proprietary footage to visually translate Austability's value proposition. The production was designed as a flagship asset for both internal alignment and external marketing.",
        outcome: "The corporate video was highly acclaimed across internal and external marketing channels, dramatically shortening the sales cycle by providing immediate conceptual clarity to new prospects. The asset became a cornerstone of Austability's institutional storytelling toolkit.",
        facts: [
            { label: "Delivered", value: "Corporate video production" },
        ],
    },
    {
        title: "Lenovo Campaigns",
        category: "B2B Demand Generation & Regulatory Logistics",
        description: "High-converting digital sales incentive campaigns backed by compliant regional promotional frameworks.",
        link: "/work/lenovo-campaigns",
        slug: "lenovo-campaigns",
        tags: ["Marketing"],
        image: "/Images/Portfolio/lenovo.webp",
        live: "",
        overview: "Radical Thinking was repeatedly commissioned by technology giant Lenovo to conceptualize and execute comprehensive B2B digital marketing and sales incentive campaigns aimed at accelerating enterprise product adoption.",
        challenge: "Driving sustained engagement in corporate B2B sales channels requires high-incentive digital mechanics, such as gamified raffles and rewards. However, deploying legal promotional draws and giveaways within the UAE requires strict, complex compliance alignment with local economic departments and government structures.",
        solution: "Radical Thinking provided an end-to-end tactical solution. We designed and developed high-impact paid banner campaigns, hyper-optimized registration landing pages, and automated backend lead-validation systems. Crucially, we architected the official compliance structure, managing the complete legal setup and operational validation required by the Dubai and UAE government entities to legally execute corporate raffles.",
        outcome: "A series of highly successful, recurring B2B campaigns that drove massive sales performance for Lenovo's product lines. By blending high-conversion digital creative work with bulletproof government compliance management, Radical Thinking delivered a friction-free, fully outsourced campaign engine for an enterprise global brand.",
        facts: [],
    },
    {
        title: "Payment Partners",
        category: "Strategic Brand Identity & Corporate Collateral",
        description: "A premium, high-trust corporate brand ecosystem for a specialized consultancy integrating payment facilities within high-risk, heavily regulated industries.",
        link: "/work/payment-partners",
        slug: "payment-partners",
        tags: ["Branding", "FinTech"],
        image: "/Images/Portfolio/Paymentpartner.webp",
        live: "",
        overview: "Payment Partners is an elite advisory firm that guides companies through the complex process of securing and integrating specialized payment infrastructure. The firm operates exclusively within high-risk, heavily regulated sectors, including dating, gaming, gambling, cryptocurrency, and digital asset exchanges. Radical Thinking was commissioned to build their foundational visual identity, premium corporate guidelines, and physical brand touchpoints from the ground up.",
        challenge: "Operating in highly scrutinized spaces like gaming, wagering, and crypto means confronting immediate skepticism from traditional banking institutions and compliance boards. The market is saturated with either overly clinical compliance firms or transient tech aesthetics. The challenge was to engineer a brand identity that projected unshakeable institutional-grade trust, bulletproof legal authority, and financial stability, while still feeling modern, progressive, and highly approachable to fast-moving digital founders.",
        solution: "Radical Thinking developed a comprehensive, premium corporate brand identity tailored for high-level financial navigation. We built a sharp, authoritative visual language anchored by deep, compliance-oriented color codes and structured typography designed to project security, transparency, and elite institutional capability. This visual ecosystem was meticulously documented into a master set of brand guidelines, defining everything from corporate color theory to layout grids for regulatory presentations, alongside premium physical collateral including custom-engineered executive business cards.",
        outcome: "The resulting brand architecture positioned Payment Partners as a premier, ironclad authority in the high-risk payment sector. The premium visual presence shifted the firm away from generic IT consultancy aesthetics, establishing them as an elite institutional player. This immediate elevation in brand equity unlocked smoother high-level onboarding with banking institutions, enhanced closing rates with enterprise exchange operators, and provided a cohesive, premium foundation ready to scale across their entire digital web infrastructure.",
        facts: [
            { label: "Delivered", value: "Brand identity, guidelines, executive collateral" },
            { label: "Sector", value: "High-risk payments & regulated fintech" },
        ],
    },
    {
        title: "Influence My World",
        category: "Data-Driven Influencer Ecosystem",
        description: "A comprehensive B2B platform and matching engine connecting global brands with targeted digital creators.",
        link: "/work/influence-my-world",
        slug: "influence-my-world",
        tags: ["Digital Platforms", "Marketing"],
        image: "/Images/Portfolio/Influence-my-world.webp",
        live: "",
        overview: "Influence My World is a data-driven digital ecosystem engineered to streamline the end-to-end relationship between commercial brands and content creators. Radical Thinking designed the complete visual framework and platform architecture.",
        challenge: "The influencer marketing space is inherently fragmented. Brands struggle to find creators who align with their specific tone of voice, target demographics, and budget constraints. Conversely, creators lack a streamlined system to cleanly present their verified rates, niche services, and availability without endless manual negotiation.",
        solution: "Radical Thinking built a centralized digital platform featuring a dual-sided portal interface. Creators can seamlessly register, verify their audiences, and input automated rate cards. Brands are granted access to an advanced, multi-layer filtering engine that intelligently matches them with the ideal influencer based on exact budgetary, regional, and product category data points.",
        outcome: "The platform delivered a highly comprehensive brand identity coupled with a powerful, automated matchmaking engine. By removing the traditional friction from influencer procurement, the system successfully enabled transparent, data-backed campaign scaling for brands and automated monetization for creators.",
        facts: [],
    },
    {
        title: "Crypto X",
        category: "Exchange Brand Engineering",
        description: "A premium visual identity and brand system for a next-generation, high-security digital asset exchange.",
        link: "/work/crypto-x",
        slug: "crypto-x",
        tags: ["FinTech", "Digital Platforms"],
        image: "/Images/Portfolio/crypto-x.webp",
        live: "",
        overview: "Crypto X is a next-generation cryptocurrency trading platform engineered for elite processing speed, uncompromising security, and an ultra-fluid user experience. Radical Thinking was brought on to engineer the foundational brand identity from the ground up.",
        challenge: "The digital asset landscape is heavily saturated with cold, repetitive tech aesthetics. Crypto X needed to position itself as an elite, premium haven that carefully vets upcoming token projects for institutional merit and utility. The challenge was to project both absolute regulatory trust and a vibrant, high-energy aesthetic that stood out in a competitive market.",
        solution: "Radical Thinking established a comprehensive brand architecture long before the final software platform went into development. We designed a sharp, high-impact visual identity and unique color palette engineered to project modern financial authority, ensuring the brand stood out as an innovative, highly sophisticated destination for serious traders.",
        outcome: "The resulting brand foundation gave Crypto X an immediate competitive advantage prior to product launch. The design assets established an aesthetic of elite security and high-energy innovation, creating a premium visual presence ready to scale across web, mobile apps, and institutional marketing campaigns.",
        facts: [],
    },
    {
        title: "Akshaak",
        category: "E-Commerce Web & Mobile Architecture",
        description: "A comprehensive, culturally resonant marketplace empowering local artisanal merchants in the UAE.",
        link: "/work/akshaak",
        slug: "akshaak",
        tags: ["Digital Platforms", "E-Commerce"],
        image: "/Images/Portfolio/Akshaak.webp",
        live: "",
        overview: "Akshaak was conceived as a premium e-commerce ecosystem dedicated exclusively to the UAE market, providing a digital home for independent creators making artisanal, culturally authentic products.",
        challenge: "Local home-based creators lacked a streamlined, unified digital avenue to scale their businesses. The challenge was to build an enterprise-grade platform that felt culturally authentic, warm, and community-driven, while simultaneously solving complex backend hurdles like automated merchant onboarding, localized delivery shipping logistics, and strict regulatory payment compliance in the UAE.",
        solution: "Radical Thinking engineered a dual-architecture platform consisting of a high-performance web application and a native mobile experience. The system features an automated storefront builder where merchants can effortlessly set up micro-stores, upload inventories, and instantly leverage fully integrated Stripe payment gateways, local government compliance checks, and automated courier shipping APIs.",
        outcome: "A vibrant, beautifully designed marketplace that perfectly captured the cultural heart and premium quality of UAE DIY craftsmanship. The platform successfully removed technical barriers for local entrepreneurs, driving immediate merchant adoption and delivering a frictionless, premium shopping experience that generated highly successful market traction.",
        facts: [],
    },
    {
        title: "Soundreaver",
        category: "Strategic E-Commerce Brand Spin-off",
        description: "An edgy, consumer-focused audio brand engineered to transition a bespoke custom shop into a scalable retail business.",
        link: "/work/soundreaver",
        slug: "soundreaver",
        tags: ["Branding", "E-Commerce"],
        image: "/Images/Portfolio/Soundreaver.webp",
        live: "",
        overview: "Soundreaver was born as a strategic brand engineering exercise for Brian's Custom Audio, a premium provider of elite, handcrafted vehicle sound systems.",
        challenge: "Bespoke, manual installation businesses are inherently unscalable; revenue is strictly limited by hours in the day and individual manual labor. The challenge was to engineer an entirely new, highly distinctive consumer brand identity that would allow the parent company to manufacture and scale mass-market speaker systems and audio products without diluting their elite custom heritage.",
        solution: "Radical Thinking conceptualized and engineered an edgy, highly disruptive brand identity named Soundreaver, inspired by the playful narrative of a mythical sound robber that hides in the wilderness to steal premium audio. We developed the entire aesthetic ecosystem, spanning high-impact social media frameworks, product packaging concepts, and an optimized web architecture ready for direct-to-consumer e-commerce scaling.",
        outcome: "A complete, market-ready brand asset package that successfully decoupled the business from purely manual service labor. The striking visual presence and unforgettable narrative provided the perfect launchpad for the company to venture into mass-market consumer electronics and scalable e-commerce distribution.",
        facts: [],
    },
    {
        title: "1001 Inventions Games",
        category: "Interactive Experiential Exhibition Development",
        description: "A high-tech, multi-device interactive installation connecting physical creativity with digital real-time projection mapping.",
        link: "/work/1001-inventions-games",
        slug: "1001-inventions-games",
        tags: ["Interactive", "Education"],
        image: "/Images/Portfolio/1001-games.webp",
        live: "",
        overview: "As part of a long-term strategic partnership with 1001 Inventions, Radical Thinking was tasked with creating an immersive educational game tracking the historical journeys and animal recordings of early historical scientists.",
        challenge: "The objective was to make historical scientific exploration deeply engaging for young children. The technical challenge lay in creating a seamless, real-time bridge between individual hand-held devices (iPads) and a massive, shared environment projection screen, ensuring zero latency while maintaining an intuitive user flow for kids.",
        solution: "Radical Thinking built a custom, fully interactive hardware-software ecosystem. We engineered a dedicated local server module capable of instantly pulling digital artwork from multiple iPads simultaneously. Children painted historical wildlife characters on their tablets and seamlessly dragged them into a living, animated digital habitat projected on the main gallery wall.",
        outcome: "An exceptionally successful experiential installation where custom-colored animals interacted within their digital habitat for several minutes. The project delivered a deeply memorable educational impact, allowing children to proudly showcase their imaginative creations to parents and teachers while interacting directly with historical narratives.",
        facts: [],
    },
    {
        title: "KFAS 1001 Inventions",
        category: "Event Web Application & PWA Development",
        description: "A high-performance, mobile-responsive Progressive Web App for a premier regional technology festival.",
        link: "/work/kfas-1001-inventions",
        slug: "kfas-1001-inventions",
        tags: ["Interactive", "Education"],
        image: "/Images/Portfolio/kfas.webp",
        live: "",
        overview: "Commissioned by 1001 Inventions in 2022, Radical Thinking was tasked with building the digital gateway for the KFA's Festival of Robotics and AI, a high-profile event designed to introduce children to the future of technology.",
        challenge: "The festival required a frictionless digital infrastructure capable of handling high volumes of traffic and immediate user registrations. The platform needed to display complex event schedules, interactive experience details, and manage time-slot bookings seamlessly, all while maintaining an incredibly engaging interface optimized for parents and educators on the move.",
        solution: "Radical Thinking engineered a fully responsive Progressive Web App (PWA) built for speed and mobile efficiency. The architecture featured an intuitive registration engine that allowed users to instantly book visiting times, manage ticketing profiles, and view real-time festival schedules directly from their mobile home screens without needing a traditional app store download.",
        outcome: "The deployment resulted in an ultra-low friction booking ecosystem. The platform successfully managed thousands of visitor registrations, optimized attendance flow through precise time-slot booking management, and provided 1001 Inventions with a highly stable, secure data infrastructure for the duration of the festival.",
        facts: [
            { label: "Delivered", value: "Progressive Web App" },
            { label: "Year", value: "2022" },
        ],
    },
    {
        title: "1001 Women",
        category: "Initiative Landing Page",
        description:
            "Landing page for a 1001 Inventions initiative spotlighting women whose impact on society, medicine, education, and science has been under-recognised.",
        link: "/work/1001-women",
        slug: "1001-women",
        tags: ["Education", "Digital Platforms"],
        image: "/Images/Portfolio/1001-Women.webp",
        live: "https://1001women.com",
        overview:
            "1001 Women is a 1001 Inventions initiative to surface women whose contributions shaped modern society, medicine, education, and science but have not received the attention they deserve. Radical Thinking delivered the public landing page as the first phase of a larger programme.",
        challenge:
            "The initiative needed a credible, public-facing entry point that could introduce the mission clearly, respect the historical weight of the subject, and leave room for a broader programme still to come.",
        solution:
            "A focused landing page that establishes the story, purpose, and presence of 1001 Women, built to launch quickly and extend as the larger project kicks off.",
        outcome:
            "Live at 1001women.com (July 2026). Foundation for the next phase of the initiative.",
        facts: [
            { label: "Technology", value: "Next.js" },
            { label: "Year", value: "2026" },
            { label: "Delivered", value: "Landing page" },
            { label: "URL", value: "1001women.com" },
            { label: "Status", value: "Live · phase one" },
        ],
    },
    {
        title: "AI Networks",
        category: "Branding & Visual Communication",
        description: "Premium visual identity and strategic brand guidelines for a high-tech AI collective.",
        link: "/work/ai-networks",
        slug: "ai-networks",
        tags: ["Branding", "AI"],
        image: "/Images/Portfolio/AINetworks-logo.webp",
        live: "",
        overview: "AI Networks was established as a high-level collaborative venture between Radical Thinking and top-tier engineering talent from Google, launching well before the modern AI boom went mainstream. The project required an elite visual foundation to match its technical pedigree.",
        challenge: "As an early pioneer in a highly technical, rapidly evolving landscape, the company needed a visual identity that felt permanent, deeply professional, and instantly recognizable. The challenge was to distill complex algorithmic capabilities and elite engineering collaboration into a clean, authoritative, and inspiring logo.",
        solution: "Following extensive industry research and conceptual iterations, Radical Thinking engineered a sophisticated design and premium color palette that explicitly communicated innovation. The visual asset was built to stand out in a crowded tech ecosystem, projecting an aura of forward-thinking authority and elite technical capability.",
        outcome: "A comprehensive, premium corporate branding package complete with strict visual identity guidelines. The resulting design framework was seamlessly translated across their web architecture and scaled across all corporate marketing collateral, providing a unified, high-tech market presence.",
        facts: [],
    },
    {
        title: "Bella Conversational AI",
        category: "Strategic Brand Identity",
        description: "A sophisticated, forward-thinking visual identity for an educational AI assistant developed ahead of the mainstream generative AI curve.",
        link: "/work/bella-conversational-ai",
        slug: "bella-conversational-ai",
        tags: ["Branding", "AI"],
        image: "/Images/Portfolio/Bella-logo.webp",
        live: "",
        overview: "Bella is an intelligent, sophisticated conversational AI assistant engineered specifically for the education sector. Radical Thinking partnered with a broader network of AI experts to establish a complete strategic brand identity and visual footprint for the assistant.",
        challenge: "The project required a brand identity that made advanced artificial intelligence feel accessible, uplifting, and genuinely cool for students. The challenge was to break away from sterile, intimidating tech aesthetics and design an inviting, highly recognizable character, specifically a smart, educated owl, that resonated with a younger academic demographic.",
        solution: "Following deep market research into youth-centric design trends, color psychology, and modern aesthetics, Radical Thinking bridged the gap between classic education and digital robotics. We developed a vibrant, playful, yet structurally precise logo centered around a stylized owl character that integrated modern chat-interface motifs.",
        outcome: "The final brand identity was remarkably vibrant and perfectly captured Bella's position as a cutting-edge educational companion. Developed long before platforms like ChatGPT or Google Gemini became household names, this pioneer identity successfully set a benchmark for early-stage conversational AI branding.",
        facts: [],
    },
    {
        title: "FlexxPay",
        category: "Promotional Video Production",
        description: "An animated promotional campaign for a financial wellness platform empowering employees with instant access to earned wages.",
        link: "/work/flexxpay",
        slug: "flexxpay",
        tags: ["FinTech", "Video"],
        image: "/Images/Portfolio/Flexxpay.webp",
        youtubeId: "TOchBsvTC5Q",
        videoCtaLabel: "Watch on YouTube",
        live: "",
        overview: "FlexxPay is a pioneering financial wellness platform that allows employees to access their earned wages in real time. Radical Thinking was brought in to create a comprehensive video production campaign that could distill this innovative concept into a highly engaging, digestible visual asset.",
        challenge: "Financial technology can often feel clinical or complex to the end-user. FlexxPay needed to clearly communicate a dual-sided value proposition in a single, cohesive informative video series: it had to simultaneously build trust with corporate employers and drive enthusiastic adoption among their employees.",
        solution: "Radical Thinking engineered and produced a dynamic series of animated explainer videos. Skipping over-engineered conceptual phases, we focused on high-impact visual storytelling that mapped out exactly what FlexxPay is and how it functions for both sides of the ecosystem. The animations broke down the mechanics of earned wage access into simple, relatable scenarios.",
        outcome: "The resulting asset package was deployed across FlexxPay's core digital channels, including YouTube, active social media campaigns, and their primary web platform. The videos significantly enhanced their B2B and B2C marketing efforts, providing the sales and growth teams with a highly effective, frictionless tool to explain the product in seconds.",
        facts: [],
    },
];
