export const portfolio = [
    {
        title: "FluffyFriends",
        category: "AI Product Engineering",
        description: "Autonomous AI pet portrait studio that generates 8K personalised artwork in under 5 minutes using n8n and Google Gemini.",
        link: "/portfolio/fluffyfriends",
        slug: "fluffyfriends",
        tags: ["AI", "Automation"],
        image: "/Images/Portfolio/fluffyfriends.webp",
        live: "https://fluffyfriends.online",
        overview: "FluffyFriends is an AI-powered pet portrait platform built by Radical Thinking. It generates personalised, high-resolution artwork from a customer photo using a fully automated workflow built on n8n and Google Gemini. No human intervention required.",
        challenge: "The market is flooded with competitors generating generic, costumed pet portraits. AI image generation is inherently unpredictable. Delivering a substandard image destroys brand trust and generates immediate refund requests. The system needed to personalise artwork and guarantee output quality without human oversight.",
        solution: "FluffyFriends runs entirely on a self-hosted n8n infrastructure. Every stage of the customer lifecycle is handled by interconnected AI agents communicating via authenticated webhooks. From smart photo validation using Gemini Flash to multi-image prompting and automated quality scoring, the system ensures only high-quality outputs reach the customer.",
        outcome: "A fully autonomous digital product that scales without adding headcount. Name-personalisation baked into the image commands a premium over generic competitors. Single-portrait entry points are engineered to convert into bundle packages via Stripe session management.",
        facts: [
            { label: "Technology", value: "Next.js, Supabase, n8n, Google Gemini, Stripe, Cloudinary" },
            { label: "Delivered", value: "Web platform, automated AI workflow, payment integration" },
            { label: "Status", value: "Live" },
            { label: "URL", value: "fluffyfriends.online" }
        ]
    },
    {
        title: "Kahulife",
        category: "AI Platform & SOS Network",
        description: "A revolutionary safety platform connecting users to emergency services instantly.",
        link: "/portfolio/kahulife",
        slug: "kahulife",
        tags: ["AI", "Digital Platforms"],
        image: "/Images/Portfolio/kahulife.webp",
        live: "https://kahulife.com",
        overview: "",
        challenge: "",
        solution: "",
        outcome: "",
        facts: []
    },
    {
        title: "Tommy & Ellie",
        category: "Generative AI Storytelling",
        description: "An interactive storytelling experience where AI generates unique narratives and illustrations for children based on their inputs.",
        link: "/portfolio/tommy-ellie",
        slug: "tommy-ellie",
        tags: ["AI", "Interactive"],
        image: "/Images/Portfolio/tommy-ellie.webp",
        live: "",
        overview: "",
        challenge: "",
        solution: "",
        outcome: "",
        facts: []
    },
    {
        title: "Animal Intelligence",
        category: "Data & AI Analysis",
        description: "An advanced platform for analysing animal behaviour using computer vision and machine learning models to provide actionable insights for researchers.",
        link: "/portfolio/animal-intelligence",
        slug: "animal-intelligence",
        tags: ["AI", "Data"],
        image: "/Images/Portfolio/animal-intelligence.webp",
        live: "",
        overview: "",
        challenge: "",
        solution: "",
        outcome: "",
        facts: []
    },
    {
        title: "Microsoft AI",
        category: "AI & Technology",
        description: "Showcasing AI capabilities through interactive digital experiences and storytelling.",
        link: "/portfolio/microsoft-ai",
        slug: "microsoft-ai",
        tags: ["AI", "Interactive"],
        image: "/Images/Portfolio/microsoft-ai.webp",
        live: "",
        overview: "",
        challenge: "",
        solution: "",
        outcome: "",
        facts: []
    },
    {
        title: "WebinarLife",
        category: "Digital Platform",
        description: "A comprehensive platform for hosting, managing, and monetising professional webinars.",
        link: "/portfolio/webinarlife",
        slug: "webinarlife",
        tags: ["Digital Platforms"],
        image: "/Images/Portfolio/webinarlife.webp",
        live: "",
        overview: "",
        challenge: "",
        solution: "",
        outcome: "",
        facts: []
    },
    {
        title: "Simon Snelder",
        category: "Personal Branding",
        description: "Strategic personal branding and digital presence for Simon Snelder, Financial Advisor.",
        link: "/portfolio/simon-snelder",
        slug: "simon-snelder",
        tags: ["Branding"],
        image: "/Images/Portfolio/simon-snelder.webp",
        live: "",
        overview: "",
        challenge: "",
        solution: "",
        outcome: "",
        facts: []
    },
    {
        title: "Austability",
        category: "Corporate Strategy & Web",
        description: "A comprehensive digital overhaul for a global defence logistics company, featuring a secure, scalable architecture and corporate storytelling.",
        link: "/portfolio/austability",
        slug: "austability",
        tags: ["Strategy", "Digital Platforms"],
        image: "/Images/Portfolio/austability.webp",
        live: "",
        overview: "",
        challenge: "",
        solution: "",
        outcome: "",
        facts: []
    },
    {
        title: "Austability Video",
        category: "Video Production",
        description: "High-fidelity video production showcasing Austability's global impact and corporate narrative.",
        link: "/portfolio/austability-video",
        slug: "austability-video",
        tags: ["Video"],
        image: "/Images/Portfolio/austability-video.webp",
        live: "",
        overview: "",
        challenge: "",
        solution: "",
        outcome: "",
        facts: []
    },
    {
        title: "Lenovo Campaigns",
        category: "Digital Marketing",
        description: "High-impact digital campaigns driving engagement and brand awareness for Lenovo.",
        link: "/portfolio/lenovo-campaigns",
        slug: "lenovo-campaigns",
        tags: ["Marketing"],
        image: "/Images/Portfolio/lenovo-campaigns.webp",
        live: "",
        overview: "",
        challenge: "",
        solution: "",
        outcome: "",
        facts: []
    },
    {
        title: "Influence My World",
        category: "Digital Platform",
        description: "Connecting brands with influencers through a data-driven digital ecosystem.",
        link: "/portfolio/influence-my-world",
        slug: "influence-my-world",
        tags: ["Digital Platforms", "Marketing"],
        image: "/Images/Portfolio/influence-my-world.webp",
        live: "",
        overview: "",
        challenge: "",
        solution: "",
        outcome: "",
        facts: []
    },
    {
        title: "Crypto X",
        category: "FinTech & Web3",
        description: "A next-generation crypto exchange platform designed for speed, security, and seamless user experience.",
        link: "/portfolio/crypto-x",
        slug: "crypto-x",
        tags: ["FinTech", "Digital Platforms"],
        image: "/Images/Portfolio/crypto-x.webp",
        live: "",
        overview: "",
        challenge: "",
        solution: "",
        outcome: "",
        facts: []
    },
    {
        title: "Akshaak",
        category: "Digital Platform",
        description: "A comprehensive digital solution and platform ecosystem.",
        link: "/portfolio/akshaak",
        slug: "akshaak",
        tags: ["Digital Platforms"],
        image: "/Images/Portfolio/akshaak.webp",
        live: "",
        overview: "",
        challenge: "",
        solution: "",
        outcome: "",
        facts: []
    },
    {
        title: "1001 Inventions Games",
        category: "Game Development",
        description: "Interactive educational gaming experiences bringing the golden age of Muslim civilisation to life.",
        link: "/portfolio/1001-inventions-games",
        slug: "1001-inventions-games",
        tags: ["Interactive", "Education"],
        image: "/Images/Portfolio/1001-inventions-games.webp",
        live: "",
        overview: "",
        challenge: "",
        solution: "",
        outcome: "",
        facts: []
    },
    {
        title: "KFAS 1001 Inventions",
        category: "Interactive Exhibition",
        description: "Digital exhibits celebrating the golden age of science in the Muslim civilisation for KFAS.",
        link: "/portfolio/kfas-1001-inventions",
        slug: "kfas-1001-inventions",
        tags: ["Interactive", "Education"],
        image: "/Images/Portfolio/kfas-1001-inventions.webp",
        live: "",
        overview: "",
        challenge: "",
        solution: "",
        outcome: "",
        facts: []
    },
    {
        title: "AI Networks",
        category: "Branding & Visual Identity",
        description: "Cutting-edge branding and visual communication for high-tech AI networking hardware.",
        link: "/portfolio/ai-networks",
        slug: "ai-networks",
        tags: ["Branding", "AI"],
        image: "/Images/Portfolio/ai-networks.webp",
        live: "",
        overview: "",
        challenge: "",
        solution: "",
        outcome: "",
        facts: []
    },
    {
        title: "Bella Conversational AI",
        category: "Strategic Brand Identity",
        description: "A strategic brand identity for a sophisticated conversational AI assistant.",
        link: "/portfolio/bella-conversational-ai",
        slug: "bella-conversational-ai",
        tags: ["Branding", "AI"],
        image: "/Images/Portfolio/bella-ai.webp",
        live: "",
        overview: "",
        challenge: "",
        solution: "",
        outcome: "",
        facts: []
    },
    {
        title: "FlexxPay",
        category: "Video Production",
        description: "Promotional video production for a financial wellness platform empowering employees with instant access to earned wages.",
        link: "/portfolio/flexxpay",
        slug: "flexxpay",
        tags: ["FinTech", "Video"],
        image: "/Images/Portfolio/flexxpay.webp",
        live: "",
        overview: "",
        challenge: "",
        solution: "",
        outcome: "",
        facts: []
    }
];